(function () {
  'use strict';
  var app = angular.module('autogeneratedForm', [
    'ui.bootstrap',
    'ngResource',
    'org.bonita.common.resources'
    ]);

  app.controller('MainCtrl', ['$scope','$location', 'contractSrvc','$window', 'humanTaskAPI', function ($scope, $location, contractSrvc, $window, humanTaskAPI) {

    var taskId = $location.search().id;

    $scope.contract = {};
    $scope.dataToSend = {};
    $scope.task = {};
    $scope.message = undefined;


    $scope.getInputName = function() {
      return 'dataToSend.attribute1';
    };


    contractSrvc.fetchContract(taskId).then(function(result){
      $scope.contract = result.data;
    });

    humanTaskAPI.get({id:taskId}, function(result){
      $scope.task = result;
    });


    $scope.postData = function() {
      $scope.message = undefined;
      contractSrvc.executeTask(taskId, $scope.dataToSend).then(function(result){
        console.log($window.top.location.href);
        $window.top.location.href = "/bonita";
      }, function(reason){
        $scope.message = reason.data.explanations;
      });
    };

  }])
  .config(['$locationProvider',function($locationProvider) {
    $locationProvider.html5Mode({
      enabled: true,
      requireBase: false
    });
  }]);


})();
