(function () {
  'use strict';
  var app = angular.module('autogeneratedForm', [
    'ui.bootstrap',
    'ngResource',
    'org.bonita.common.resources'
    ]);

  app.controller('MainCtrl', ['$scope','$location', 'contractSrvc', function ($scope, $location, contractSrvc) {

    var taskId = $location.search().id;

    $scope.contract = {};

    contractSrvc.fetchContract(taskId).then(function(result){
      $scope.contract = result.data;
    });

  }])
  .config(['$locationProvider',function($locationProvider) {
    $locationProvider.html5Mode({
      enabled: true,
      requireBase: false
    });
  }]);


})();
