(function () {
  'use strict';
  angular.module('autogeneratedForm').factory('contractSrvc', ['$http', function($http) {

    return {
      fetchContract: function (taskId) {
        // fetch contract from server
        return $http({
          url: '/bonita/API/bpm/userTask/' + taskId + '/contract',
          method: 'GET'
        });
      }
    };
  }]);
})();
